StoreManager/StoreManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_store.urls'))
]

StoreManager/app_store/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

from .views import register_view, CustomLoginView, CustomLogoutView, ProfileView, ProviderListView, \
    GoodCategoryListView, delete_provider, edit_provider, GoodsListView, delete_good, edit_good, delete_category, \
    GoodDetailView, CreateSupplyView, SupplyListView, CreateSaleView, SalesListView, GetGoodPriceView
from .api_views import ProviderAPIView, GoodAPIView, ProviderDetailAPI, GoodDetailAPI, SaleDetailAPI

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('register/', register_view, name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('api/providers/', ProviderAPIView.as_view(), name='api_providers_list'),
    path('api/providers/<int:pk>/', ProviderDetailAPI.as_view(), name='api_provider_detail'),
    path('api/goods/', GoodAPIView.as_view(), name='api_goods_list'),
    path('api/sales/', GoodAPIView.as_view(), name='api_sales_list'),
    path('api/goods/<int:pk>/', GoodDetailAPI.as_view(), name='api_good_detail'),
    path('api/sales/<int:pk>/', SaleDetailAPI.as_view(), name='api_sale_detail'),
    path('providers_list/', ProviderListView.as_view(), name='providers_list'),
    path('delete_provider/<int:provider_id>/', delete_provider, name='delete_provider'),
    path('edit_provider/<int:provider_id>/', edit_provider, name='edit_provider'),
    path('categories_list/', GoodCategoryListView.as_view(), name='categories_list'),
    path('delete_category/<int:category_id>/', delete_category, name='delete_category'),
    path('goods_list/', GoodsListView.as_view(), name='goods_list'),
    path('delete_good/<int:good_id>/', delete_good, name='delete_good'),
    path('edit_good/<int:good_id>/', edit_good, name='edit_good'),
    path('good/<int:pk>/', GoodDetailView.as_view(), name='good_detail'),
    path('create_supply/', CreateSupplyView.as_view(), name='create_supply'),
    path('supply_list/', SupplyListView.as_view(), name='supply_list'),
    path('create_sale/', CreateSaleView.as_view(), name='create_sale'),
    path('get_good_price/<int:good_id>/', GetGoodPriceView.as_view(), name='get_good_price'),
    path('sales_list/', SalesListView.as_view(), name='sales_list'),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

StoreManager/app_store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import F


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='пользователь')
    birthday = models.DateField(verbose_name='дата рождения')
    phone = models.CharField(max_length=11)
    position = models.CharField(max_length=30, verbose_name='должность')

    def __str__(self):
        return f'{self.user.email}'

    class Meta:

        db_table = 'profile'
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

class GoodCategory(models.Model):

    name = models.CharField(verbose_name='категория товара', max_length=50,
                            db_index=True)

    class Meta:

        db_table = 'category'
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


    def __str__(self):
        return f'{self.name}'


class Provider(models.Model):

    name = models.CharField(max_length=50, verbose_name='поставщик')
    phone_number = models.CharField(max_length=11, verbose_name='телефон поставщика')
    email = models.EmailField(max_length=50, verbose_name='почта')
    contact_person = models.CharField(max_length=255, verbose_name='контактное лицо')
    categories = models.ManyToManyField(GoodCategory, verbose_name='категории')

    class Meta:

        db_table = 'providers'
        verbose_name = 'поставщик'
        verbose_name_plural = 'поставщики'

    def __str__(self):
        return f'{self.name}'

class Good(models.Model):

    name = models.CharField(max_length=30, db_index=True,
                            verbose_name='название товара')
    part_number = models.CharField(max_length=10, verbose_name='артикул', default='')
    category = models.ForeignKey(GoodCategory, on_delete=models.CASCADE,
                                 verbose_name='категория',
                                 null=True)

    selling_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='цена продажи')
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='закупочная цена')
    description = models.TextField(verbose_name='описание товара')
    image = models.ImageField(upload_to='goods/',
                              verbose_name='картинка товара',blank=True, null=True)
    quantity = models.IntegerField(verbose_name='кол-во товара', default=0)
    sold_quantity = models.IntegerField(default=0, verbose_name='кол-во продано')
    manufacturer = models.CharField(max_length=30, verbose_name='производитель')

    def new_supply(self, num):
        self.quantity = F('quantity') + num
        self.save(update_fields=['quantity'])

    def make_sale(self, num):
        if self.quantity < num:
            raise ValueError("Недостаточно товара в наличии для продажи")
        self.quantity = F('quantity') - num
        self.sold_quantity = F('sold_quantity') + num
        self.save(update_fields=['quantity', 'sold_quantity'])


    class Meta:

        db_table = 'good'
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return f'{self.name}'



class Supply(models.Model):
    supply_date = models.DateTimeField(auto_now_add=True)
    goods = models.ManyToManyField('Good', through='SupplyGood')
    provider = models.ForeignKey('Provider', on_delete=models.CASCADE, verbose_name='поставщик')

    class Meta:
        db_table = 'supplies'
        verbose_name = 'поставка'
        verbose_name_plural = 'поставки'

    def __str__(self):
        return f'Поставка от {self.supply_date}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        for supply_good in self.supplygood_set.all():
            supply_good.good.new_supply(supply_good.quantity)
            supply_good.good.save()

    def supply_total_cost(self):
        return sum(good.total_cost() for good in self.supplygood_set.all())

class SupplyGood(models.Model):
    supply = models.ForeignKey(Supply, on_delete=models.CASCADE)
    good = models.ForeignKey('Good', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.good.new_supply(self.quantity)

    def total_cost(self):
        return self.good.purchase_price * self.quantity


class Sale(models.Model):
    goods = models.ManyToManyField('Good', through='SaleItem')
    sale_date = models.DateTimeField(auto_now_add=True, verbose_name='дата продажи')
    discount = models.DecimalField(max_digits=5, decimal_places=2, default=0, verbose_name='скидка (в процентах)')
    payment_method = models.CharField(max_length=50, default='Наличные', choices=[('Наличные', 'Наличные'), ('Карта', 'Карта')], verbose_name='способ оплаты')
    final_cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='итоговая стоимость', default=0)

    def sale_total_cost(self):
        return sum(item.total_cost() for item in self.saleitem_set.all())

    def final_cost_with_discount(self):
        return self.sale_total_cost() * (1 - self.discount / 100)

    def save(self, *args, **kwargs):
        self.final_cost = self.final_cost_with_discount()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Продажа от {self.sale_date}'

    class Meta:
        db_table = 'sales'
        verbose_name = 'продажа'
        verbose_name_plural = 'продажи'



class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    good = models.ForeignKey('Good', on_delete=models.CASCADE, verbose_name='товар')
    quantity = models.PositiveIntegerField(verbose_name='количество')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.good.make_sale(self.quantity)

    def total_cost(self):
        return self.good.selling_price * self.quantity
    class Meta:
        db_table = 'sold_goods'
        verbose_name = 'проданный товар'
        verbose_name_plural = 'проданные товары'

    def __str__(self):
        return f'{self.good.name} ({self.quantity} шт.)'

StoreManager/app_store/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MinValueValidator, MaxValueValidator, MaxLengthValidator
from django.forms import inlineformset_factory

from .models import User, Profile, Good, GoodCategory, Provider, Supply, Sale, SupplyGood, SaleItem
from django import forms
from django.utils.translation import gettext_lazy as _



class UserForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'style': 'width: 250px; margin: 0 auto;'}),
    )
    password2 = forms.CharField(
        label=_("Подтверждение пароля"),
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'style': 'width: 250px; margin: 0 auto;'}),
        strip=False,
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        labels = {
            'username': _('Имя пользователя'),
            'first_name': _('Имя'),
            'last_name': _('Фамилия'),
            'email': _('Email'),
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 250px; margin: 0 auto;'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 250px; margin: 0 auto;'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 250px; margin: 0 auto;'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'style': 'width: 250px; margin: 0 auto;'}),
        }


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('birthday', 'phone', 'position')
        labels = {
            'birthday': _('Дата рождения'),
            'phone': _('Номер телефона'),
            'position': _('Должность')
        }
        widgets = {
            'birthday': forms.DateInput(attrs={'class': 'form-control',
                                               'style': 'width: 250px; margin: 0 auto;'}),
            'phone': forms.TextInput(attrs={'class': 'form-control',
                                                           'style': 'width: 250px; margin: 0 auto;'}),
            'position': forms.TextInput(attrs={'class': 'form-control',
                                            'style': 'width: 250px; margin: 0 auto;'}),
        }
class GoodForm(forms.ModelForm):
    class Meta:
        model = Good
        exclude = ['sold_quantity', 'quantity']
        labels = {
            'name': _('Название товара'),
            'part_number': _('Артикул'),
            'category': _('Категория'),
            'selling_price': _('Цена продажи'),
            'purchase_price': _('Закупочная цена'),
            'description': _('Описание товара'),
            'image': _('Картинка товара'),
            'manufacturer': _('Производитель'),
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                           'style': 'width: 250px; margin: 0 auto;'}),
            'part_number': forms.TextInput(attrs={'class': 'form-control',
                                                  'style': 'width: 250px; margin: 0 auto;'}),
            'category': forms.Select(attrs={'class': 'form-select',
                                            'style': 'width: 250px; margin: 0 auto;'}),
            'selling_price': forms.NumberInput(attrs={'class': 'form-control',
                                                      'style': 'width: 250px; margin: 0 auto;'}),
            'purchase_price': forms.NumberInput(attrs={'class': 'form-control',
                                                       'style': 'width: 250px; margin: 0 auto;'}),
            'description': forms.Textarea(attrs={'class': 'form-control',
                                                 'style': 'width: 250px; height: 50px; margin: 0 auto;'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control',
                                                     'style': 'width: 250px; margin: 0 auto;'}),
            'manufacturer': forms.TextInput(attrs={'class': 'form-control',
                                            'style': 'width: 250px; margin: 0 auto;'}),
        }


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = ['name', 'contact_person', 'phone_number', 'email', 'categories']
        labels = {
            'name': _('Название поставщика'),
            'contact_person': _('Контактное лицо'),
            'phone_number': _('Номер телефона'),
            'email': _('Электронная почта'),
            'categories': _('Категории товаров'),
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                           'style': 'width: 250px; margin: 0 auto;'}),
            'contact_person': forms.TextInput(attrs={'class': 'form-control',
                                                     'style': 'width: 250px; margin: 0 auto;'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control',
                                                   'style': 'width: 250px; margin: 0 auto;'}),
            'email': forms.EmailInput(attrs={'class': 'form-control',
                                             'style': 'width: 250px; margin: 0 auto;'}),
            'categories': forms.SelectMultiple(attrs={'class': 'form-select',
                                                      'style': 'width: 250px; margin: 0 auto;'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categories'].queryset = GoodCategory.objects.all()

class GoodCategoryForm(forms.ModelForm):
    class Meta:
        model = GoodCategory
        fields = ['name']
        labels = {
            'name': _('Категория товара')
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control',
                                        'style': 'width: 200px; margin: 0 auto;'})
        }

class SupplyForm(forms.ModelForm):
    class Meta:
        model = Supply
        fields = ['provider']
        labels = {
            'provider': _('Поставщик')
        }
        widgets = {
            'provider': forms.Select(attrs={'class': 'form-select',
                                            'style': 'width: 250px; margin: 0 auto;'})
        }

class SupplyGoodForm(forms.ModelForm):
    class Meta:
        model = SupplyGood
        fields = ['good', 'quantity']
        labels = {
            'good': _('Товар'),
            'quantity': _('Количество товаров')
        }
        widgets = {
            'good': forms.Select(attrs={'class': 'form-select',
                                        'style': 'width: 250px; margin: 0 auto;'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control',
                                                 'style': 'width: 250px; margin: 0 auto;'}),
        }

SupplyGoodFormSet = inlineformset_factory(Supply, SupplyGood, form=SupplyGoodForm, extra=5, can_delete=False)

class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ['discount', 'payment_method']
        labels = {
            'discount': _('Скидка'),
            'payment_method': _('Способ оплаты')
        }
        widgets = {
            'discount': forms.NumberInput(attrs={'class': 'form-control',
                                                 'step': 1,
                                                 'style': 'width: 250px; margin: 0 auto;', 'min': 0, 'max': 50, 'max_length': 3}),
            'payment_method' : forms.Select(attrs={'class': 'form-select', 'style': 'width: 250px; margin: 0 auto;'}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['discount'].validators = [MinValueValidator(0), MaxValueValidator(50), MaxLengthValidator(2)]


class SaleItemForm(forms.ModelForm):
    class Meta:
        model = SaleItem
        fields = ['good', 'quantity']
        labels = {
            'good': _('Товар'),
            'quantity': _('Количество')
        }
        widgets = {
            'good': forms.Select(attrs={'class': 'form-select', 'style': 'width: 250px;  margin: 0 auto;'}),
            'quantity': forms.NumberInput(attrs={'max_length': 2, 'class': 'form-control', 'style': 'width: 250px; margin: 0 auto;'}),
        }


SaleItemFormSet = inlineformset_factory(Sale, SaleItem, form=SaleItemForm, extra=3, can_delete=False)

StoreManager/app_store/templates/app_store/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    {{ form.media }}
    <meta charset="UTF-8">
    <title>StoreManager</title>
    {% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'app_store/css/style1.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% endblock %}
</head>
<body style="background: rgb(194,203,214);
background: radial-gradient(circle, rgba(194,203,214,1) 54%, rgba(129,143,167,1) 100%);">
{% block header %}
    <header class="header">
        <div class="d-flex justify-content-around mb-3">
            <h1 style="font-family: Brush Script MT, cursive; color: white;">Store</h1>
                <div class="linksDiv">
                    <div class="linkItem dropdown">
                        <a class="headerText dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                           {% trans "Продажи" %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'sales_list' %}">{% trans "Список продаж" %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'create_sale' %}">{% trans "Создание продажи" %}</a></li>
                        </ul>
                    </div>
                    <div class="linkItem dropdown">
                        <a class="headerText dropdown-toggle" href="#" role="button" id="dropdownMenuLink1" data-bs-toggle="dropdown" aria-expanded="false">
                            {% trans "Поставки" %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink1">
                            <li><a class="dropdown-item" href="{% url 'providers_list' %}">{% trans "Список поставщиков" %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'create_supply' %}">{% trans "Создание поставки" %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'supply_list' %}">{% trans "Список поставок" %}</a></li>
                        </ul>
                    </div>
                    <div class="linkItem dropdown">
                        <a class="headerText dropdown-toggle" href="#" role="button" id="dropdownMenuLink2" data-bs-toggle="dropdown" aria-expanded="false">
                            {% trans "Товары" %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink2">
                            <li><a class="dropdown-item" href="{% url 'goods_list' %}">{% trans "Список товаров" %}</a></li>
                            <li><a class="dropdown-item" href="{% url 'categories_list' %}">{% trans "Категории товаров" %}</a></li>
                        </ul>
                    </div>
                </div>
            <div class="d-flex justify-content-between align-items-center">
                {% if request.user.is_authenticated %}

            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle mb-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans "Действия" %}
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" type="button" href="{% url 'profile' %}">{% trans "Профиль" %}</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">{% trans "Выйти" %}</a></li>
                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#apiModal">API List</a>
                </li>
                <li role="separator" class="dropdown-divider"></li>
                <li>
                  <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select name="language" class="dropdown-item" onchange="this.form.submit()">
                      {% get_current_language as LANGUAGE_CODE %}
                      {% get_available_languages as LANGUAGES %}
                      {% get_language_info_list for LANGUAGES as languages %}
                      {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                          {{ language.name_local }}
                        </option>
                      {% endfor %}
                    </select>
                  </form>
                </li>
              </ul>
            </div>

                {% else %}
                    <div style="width: 100px;">
                        <a style="color: #e7eaf6;" class="me-4" href="{% url 'login' %}">{% trans "Войти" %}</a>
                        <a style="color: #e7eaf6;" href="{% url 'register' %}">{% trans "Регистрация" %}</a>
                    </div>
                 <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    <select name="language" class="form-select" onchange="this.form.submit()">
                      {% get_current_language as LANGUAGE_CODE %}
                      {% get_available_languages as LANGUAGES %}
                      {% get_language_info_list for LANGUAGES as languages %}
                      {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                          {{ language.name_local }}
                        </option>
                      {% endfor %}
                    </select>
                  </form>

                {% endif %}
            </div>
        </div>
    </header>

    <div class="modal fade" id="apiModal" tabindex="-1" aria-labelledby="apiModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div style="background-color: #113f67;" class="modal-content">
                <div class="modal-header">
                    <h5 style="color: white;" class="modal-title" id="apiModalLabel">API List</h5>
                </div>
                <div style="background: rgb(194,203,214);
background: radial-gradient(circle, rgba(194,203,214,1) 54%, rgba(129,143,167,1) 100%);" class="modal-body">
                    <ul>
                        <li><a style="text-decoration: none; color: #113f67;" href="{% url 'api_providers_list' %}"><strong>Providers API</strong></a></li>
                        <li><a style="text-decoration: none; color: #113f67;" href="{% url 'api_goods_list' %}"><strong>Goods API</strong></a></li>
                        <li><a style="text-decoration: none; color: #113f67;" href="{% url 'api_sales_list' %}"><strong>Sales API</strong></a></li>
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light redBtn" data-bs-dismiss="modal">X</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}

{% endblock %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js">  </script>
{% endblock %}
</body>
</html>

StoreManager/app_store/templates/app_store/categories_list.html
{% extends 'app_store/base.html' %}
{% load static %}
{% load i18n %}

{% block links %}
  <link rel="stylesheet" type="text/css" href="{% static 'app_store/css/style1.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
{% endblock %}

{% block content %}
  <h1 class="ms-5">{% trans "Категории товаров" %}</h1>
  <div style="display: flex; margin: 0 auto; width: 1000px;">
    <div class="addСategory mt-5">
      <h5>{% trans "Добавить новую категорию" %}</h5>
      <form method="post" action="{% url 'categories_list' %}">
        {% csrf_token %}
        <div class="form-group">
          <h6>{{ form.name.label_tag }}</h6>
          {{ form.name }}
        </div>
        <button type="submit"  class="btn btn-primary mt-3">{% trans "Добавить" %}</button>
      </form>
    </div>
    <div class="smallTableContainer">
      <table class="table mt-5 table-sm table-secondary table-hover table-bordered text-center">
        <thead class="table-primary">
          <tr>
            <th>{% trans "Название категории" %}</th>
            <th>{% trans "Действие" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for category in categories %}
            <tr>
              <td>{{ category.name }}</td>
              <td>
                <form method="post" action="{% url 'delete_category' category.id %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm ">{% trans "Удалить" %}</button>
              </form>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="2">{% trans "Нет категорий" %}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

StoreManager/app_store/templates/app_store/create_supply.html
{% extends 'app_store/base.html' %}
{% load static %}
{% load i18n %}


{% block content %}
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

    <div class="supplyDiv">
        <h2 style="color: #e7eaf6;">{% trans "Создание поставки" %}</h2>
        <form method="post" id="supply-form">
            {% csrf_token %}
            <div class="supplyFormD pt-3">
                <div class="form-group">
                    <h5>{{ supply_form.provider.label|safe }}</h5>
                    {{ supply_form.provider }}
                </div>
                <h2>{% trans "Выбор товаров" %}</h2>
                <div id="goods-formset">
                    {{ supply_good_formset.management_form }}
                    {% for form in supply_good_formset %}
                        <div class="good-form {% if not forloop.first %}hidden{% endif %}">
                            <div class="form-group mb-3 mt-3">
                                <h5>{{ form.good.label|safe }}</h5>
                                {{ form.good }}
                            </div>
                            <div class="form-group">
                                <h5>{{ form.quantity.label|safe }}</h5>
                                {{ form.quantity }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="d-grid gap-2 col-6 mx-auto mt-4">
                    <button class="btn btn-primary " type="button" id="show-forms">{% trans "Добавить еще товар" %}</button>
                    <input class="btn btn-primary mb-3 btnAdd" type="submit" value="{% trans 'Сохранить' %}">
                </div>
            </div>
        </form>
    </div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'app_store/js/supply.js' %}"></script>
{% endblock %}

StoreManager/app_store/templates/app_store/sales_list.html
{% extends 'app_store/base.html' %}
{% load i18n %}


{% block content %}
<h1 class="ms-5 mb-4">{% trans "Список продаж" %}</h1>
<div class="ms-5">
    <h4>{% trans "Сумма всех продаж" %}: <strong>{{ total_sum }} RUB.</strong></h4>
</div>
<div class="container mt-5 mb-4">
    <div class="row row-cols-1 row-cols-md-3 g-3">
        {% for sale in sales %}
        <div class="col">
            <div class="card h-100">
                <div class="card-header" style="background-color: #113f67; color: #e7eaf6;">
                    <h5 class="card-title">{% trans "Продажа" %} №{{ sale.id }}</h5>
                </div>
                <div class="card-body" style="background-color: #6F94D2;">
                    <p style="font-size: 18px;" class="card-text">
                        {% trans "Дата" %}:<strong> {{ sale.sale_date }}</strong><br>
                        {% trans "Скидка" %}:<strong> {{ sale.discount }} %</strong><br>
                        {% trans "Способ оплаты" %}:<strong> {{ sale.get_payment_method_display }}</strong>
                    </p>
                    <h5>{% trans "Товары" %}:</h5>
                    <ul class="list-group list-group-flush">
                        {% for item in sale.saleitem_set.all %}
                        <li  style="background-color: #e7eaf6; border-radius: 10px;"  class="list-group-item mb-1">
                            {{ item.good.name }} - {{ item.quantity }} шт.
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-footer" style="background-color: #113f67; color: #e7eaf6;">
                    <h5>{% trans "Финальная стоимость с учетом скидки" %}:</h5>
                    <p class="card-text mb-2"><strong>{{ sale.final_cost|floatformat:2 }} RUB. </strong></p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-md-12">
            <p>{% trans "Нет продаж" %}.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}